name: Update Profile SVG

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run update script
        env:
          MY_PAT: ${{ secrets.readme }}
        run: python update_svg.py
      - name: Show git remote
        run: git remote -v
      - name: Set remote URL to use PAT
        run: git remote set-url origin https://itsmeyessir:${{ secrets.readme }}@github.com/itsmeyessir/itsmeyessir.git
      - name: Unset git credential helper
        run: git config --unset-all credential.helper || echo 'No credential helper set'
      - name: Commit and push changes
        run: |
          git config user.name 'itsmeyessir'
          git config user.email 'espaldonrobbie88@gmail.com'
          git add dark_mode.svg light_mode.svg
          git commit -m 'Update profile SVGs' || echo 'No changes to commit'
          git push origin main
