name: Update Profile SVG

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Use your PAT for authentication during checkout
          token: ${{ secrets.readme }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        # MY_PAT is still needed here for your Python script if it makes API calls
        env:
          MY_PAT: ${{ secrets.readme }} 
        run: python update_svg.py

      - name: Commit and push changes
        run: |
          git config user.name 'itsmeyessir'
          git config user.email 'espaldonrobbie88@gmail.com'
          git add dark_mode.svg light_mode.svg
          git commit -m 'Update profile SVGs' || echo 'No changes to commit'
          # Push using the token provided to actions/checkout
          git push